<a href="https://colab.research.google.com/github/taha2samy/principles-of-statistics/blob/master/Tutorial_of_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tutorial of NumPy**

numpylogo.svg

<svg src = 'https://numpy.org/doc/stable/_static/numpylogo.svg'><svg>

## Upgrade NumPy

In [1]:
!pip install --upgrade numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 38.4 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.25.2
    Uninstalling numpy-1.25.2:
      Successfully uninstalled numpy-1.25.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lida 0.0.10 requires fastapi, which is not installed.
lida 0.0.10 requires kaleido, which is not installed.
lida 0.0.10 requires python-multipart, which is not installed.
lida 0.0.10 requires uvicorn, which is not installed.


## Import NumPy

In [2]:
import numpy as np

# Create NumPy Array




In [3]:
newList= [1,2,3,4,5,6,7]
array_1dim = np.array(newList,dtype=np.dtypes.Int64DType)
array_2dim= np.array([[1,2,3],[4,5,6],[7,8,9]])
array_3dim=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(array_1dim,'\n',array_1dim,'\n',array_3dim)

[1 2 3 4 5 6 7] 
 [1 2 3 4 5 6 7] 
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


## What’s the difference between a Python list and a NumPy array?

NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous. The mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren’t homogeneous.

## Why use NumPy?

NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

## What is an array?

An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array dtype.

An array can be indexed by a tuple of nonnegative integers, by booleans, by another array, or by integers. The rank of the array is the number of dimensions. The shape of the array is a tuple of integers giving the size of the array along each dimension.

One way we can initialize NumPy arrays is from Python lists, using nested lists for two- or higher-dimensional data.


## Properties of Array

In [4]:
print(f'{array_1dim.ndim} {array_2dim.ndim} {array_3dim.ndim}')

1 2 3


In [5]:
print(f'{array_1dim.shape} {array_2dim.shape} {array_3dim.shape}')

(7,) (3, 3) (2, 3, 3)


In [6]:
array_1dim.size

7

In [7]:
array_1dim.nbytes

56

In [8]:
array_1dim.nbytes/array_1dim.size # size of one unit of data type

8.0

In [9]:
array_1dim.dtype

dtype('int64')

In [10]:
for i,v in {k:v for k,v in np.sctypes.items()}.items():
  print(i,v)

int [<class 'numpy.int8'>, <class 'numpy.int16'>, <class 'numpy.int32'>, <class 'numpy.int64'>]
uint [<class 'numpy.uint8'>, <class 'numpy.uint16'>, <class 'numpy.uint32'>, <class 'numpy.uint64'>]
float [<class 'numpy.float16'>, <class 'numpy.float32'>, <class 'numpy.float64'>, <class 'numpy.longdouble'>]
complex [<class 'numpy.complex64'>, <class 'numpy.complex128'>, <class 'numpy.clongdouble'>]
others [<class 'bool'>, <class 'object'>, <class 'bytes'>, <class 'str'>, <class 'numpy.void'>]


## Generating numbers

In [11]:
# i range
print([*range(1,100)]) # only integer numbers

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [12]:
np.arange(1,100,40)

array([ 1, 41, 81])

In [13]:
np.linspace(1,100,11)

array([  1. ,  10.9,  20.8,  30.7,  40.6,  50.5,  60.4,  70.3,  80.2,
        90.1, 100. ])

In [14]:
np.logspace(1,10,10)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

## Generating Array ones and zeros




In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.empty((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.full((2,2), 2)

array([[2, 2],
       [2, 2]])

In [18]:
np.ones((3,3,))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

## Generating random Array

In [21]:
np.random.random((1,2))


array([[0.71257618, 0.90375463]])

In [22]:
np.random.random(12)

array([0.22811218, 0.45447276, 0.44507609, 0.88675864, 0.6428596 ,
       0.12067598, 0.42744196, 0.067778  , 0.17937835, 0.49788459,
       0.99755744, 0.54922233])

In [23]:
np.random.random()

0.416263424358722

In [24]:
np.random.randn(3,3)#Return a sample (or samples) from the “standard normal” distribution.

array([[ 0.76318544, -0.88901796,  0.03413062],
       [-1.38111661, -1.37909874,  0.27756097],
       [-0.04830896, -0.88725357, -0.52337017]])

In [25]:
np.random.randint(0,100,(3,3))

array([[61, 72, 62],
       [68, 30, 19],
       [35, 75, 44]])

## Slicing and Indexing

In [26]:
test = np.random.randint(0,100,(3,3))

In [27]:
test

array([[50, 78, 11],
       [65, 28, 40],
       [17, 18,  2]])

In [28]:
test[0,0]
test[0,0]=1

In [29]:
test.item(6)

17

In [30]:
test.item((1,1))

28

In [31]:
test[1,0::1] #row,column row 0 , column 1

array([65, 28, 40])

In [32]:
test.take([0,3])

array([ 1, 65])

In [33]:
test.put([1,2,3],[25,10,10]) # index and values

In [34]:
test

array([[ 1, 25, 10],
       [10, 28, 40],
       [17, 18,  2]])

In [35]:
test[::-1,::-1]

array([[ 2, 18, 17],
       [40, 28, 10],
       [10, 25,  1]])

## Reshaping

In [36]:
np.linspace(1,100,9).reshape(3,3)

array([[  1.   ,  13.375,  25.75 ],
       [ 38.125,  50.5  ,  62.875],
       [ 75.25 ,  87.625, 100.   ]])

In [37]:
a=np.linspace(1,100,9)
a.resize((3,3))

In [38]:
test = np.random.randint(1,100,(3,3))
test

array([[52, 11, 75],
       [99, 91, 51],
       [62, 49, 55]])

In [39]:
test.swapaxes(0,1)

array([[52, 99, 62],
       [11, 91, 49],
       [75, 51, 55]])

In [40]:
test.transpose()

array([[52, 99, 62],
       [11, 91, 49],
       [75, 51, 55]])

'C': Flatten the array in row-major (C-style) order. This means elements are read row by row first, then column by column.

'F': Flatten the array in column-major (Fortran-style) order. This means elements are read column by column first, then row by row.

'A': Flatten the array in column-major order if the array is Fortran contiguous in memory, otherwise flatten it in row-major order.

'K': Flatten the array in the order the elements occur in memory.

The default value is 'C', which means flattening the array in row-major order.








In [41]:
test.flatten('K')

array([52, 11, 75, 99, 91, 51, 62, 49, 55])

In [42]:
test.sort(axis=0)
test

array([[52, 11, 51],
       [62, 49, 55],
       [99, 91, 75]])

## Stacking

In [43]:
test = np.random.randint(0,100,(3,3))
test1=np.random.randint(0,100,(3,1))
print(test,test1)

[[69 37 62]
 [52 48 12]
 [59 26 76]] [[22]
 [89]
 [40]]


In [44]:
np.hstack((test,test1))

array([[69, 37, 62, 22],
       [52, 48, 12, 89],
       [59, 26, 76, 40]])

In [45]:
np.vstack((test,test1.transpose()))

array([[69, 37, 62],
       [52, 48, 12],
       [59, 26, 76],
       [22, 89, 40]])

In [46]:
np.delete(test,0,axis=0)

array([[52, 48, 12],
       [59, 26, 76]])

In [47]:
# المصفوفات الأساسية
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# دمج المصفوفات عبر الأعمدة باستخدام np.column_stack()
result_column = np.column_stack((arr1, arr2))
print("Using np.column_stack():")
print(result_column)

# دمج المصفوفات عبر الصفوف باستخدام np.row_stack()
result_row = np.row_stack((arr1, arr2))
print("\nUsing np.row_stack():")
print(result_row)

Using np.column_stack():
[[1 4]
 [2 5]
 [3 6]]

Using np.row_stack():
[[1 2 3]
 [4 5 6]]


In [48]:

# إنشاء مصفوفة عشوائية بحجم 4x4
arr = np.random.randint(1, 10, (4, 4))
print("Original Array:")
print(arr)
print()

# تقسيم المصفوفة إلى قسمين أفقيين
h_splits = np.hsplit(arr, 2)
print("Horizontal Split:")
for split in h_splits:
    print(split)
print()

# تقسيم المصفوفة إلى قسمين رأسيين
v_splits = np.vsplit(arr, 2)
print("Vertical Split:")
for split in v_splits:
    print(split)


Original Array:
[[8 3 2 6]
 [2 1 9 9]
 [5 1 7 2]
 [6 3 6 2]]

Horizontal Split:
[[8 3]
 [2 1]
 [5 1]
 [6 3]]
[[2 6]
 [9 9]
 [7 2]
 [6 2]]

Vertical Split:
[[8 3 2 6]
 [2 1 9 9]]
[[5 1 7 2]
 [6 3 6 2]]


## Copy

In [49]:
arr = np.random.randint(1, 10, (4, 4))
arr.view()
ex = arr.copy()
ex

array([[6, 5, 6, 4],
       [8, 9, 6, 6],
       [4, 8, 6, 4],
       [1, 3, 3, 1]])

In [50]:
# Original 2D array
original_array = np.array([[1, 2, 3],
                           [4, 5, 6]])

# Shallow copy using copy()
shallow_copy = original_array.view()

# Deep copy using copy() with deep=True
deep_copy = original_array.copy()

# Modify the first nested array in the copies
shallow_copy[0][0] = 100
deep_copy[0][0] = 1000

# Print the original array and the copies
print("Original Array:")
print(original_array)
print("\nShallow Copy (modified first element of the first nested array):")
print(shallow_copy)
print("\nDeep Copy (modified first element of the first nested array):")
print(deep_copy)


Original Array:
[[100   2   3]
 [  4   5   6]]

Shallow Copy (modified first element of the first nested array):
[[100   2   3]
 [  4   5   6]]

Deep Copy (modified first element of the first nested array):
[[1000    2    3]
 [   4    5    6]]


# Basic Math

In [51]:
arr_1 = np.array([1,2,3,4,5])
arr_2= np.array([5,6,7,8,9])

In [52]:
arr_1/arr_2

array([0.2       , 0.33333333, 0.42857143, 0.5       , 0.55555556])

In [53]:
arr_1.max()

5

In [54]:
arr_1.min()

1

In [55]:
arr_1.mean()

3.0

In [56]:
arr_1.std()

1.4142135623730951

In [57]:
arr_1.sum() # accept access

15

In [58]:
arr_1 = np.random.randint(0,100,(5,5))
arr_1

array([[75, 33, 43, 79, 50],
       [36, 36, 10, 47, 18],
       [57, 65, 26, 73, 21],
       [34,  0,  7, 93, 63],
       [94, 65, 90, 48, 20]])

In [59]:
arr_1.sum(axis=0)

array([296, 199, 176, 340, 172])

In [60]:
arr_1.cumsum()

array([  75,  108,  151,  230,  280,  316,  352,  362,  409,  427,  484,
        549,  575,  648,  669,  703,  703,  710,  803,  866,  960, 1025,
       1115, 1163, 1183])

In [61]:
np.power(2,3)

8

In [62]:
np.sqrt(2)

1.4142135623730951

In [63]:
np.cbrt(2)

1.2599210498948734

In [64]:
np.abs(-1)

1

In [65]:
np.absolute(-1)

1

In [66]:
np.exp(1)

2.718281828459045

In [67]:
np.pi

3.141592653589793

In [68]:
np.log2(2)

1.0

In [69]:
np.log(11)/np.log(11)

1.0

In [70]:
arr = np.array([24, 36, 48])
gcd = np.gcd.reduce(arr)
lcm = np.lcm.reduce(arr)
print("GCD of the array is:", gcd)
print("LCM of the array is:", lcm)

GCD of the array is: 12
LCM of the array is: 144


In [71]:
np.floor(1.2)

1.0

In [72]:
np.ceil(1.3)

2.0

In [73]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

argmax_index = np.argmax(arr)
print("arg max", argmax_index)

argmin_index = np.argmin(arr)
print("arg min", argmin_index)

arg max 5
arg min 0


In [74]:
np.round(np.cos(np.deg2rad(90)))

0.0

In [75]:
np.rad2deg(np.pi)

180.0

### on Vector

In [76]:

vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

dot_product = np.dot(vector_a, vector_b)

# Print the dot product
print("Dot product:", dot_product)


Dot product: 32


In [77]:
vector = np.array([1, 2, 3])


In [78]:


# Calculate the norm of the vector using the numpy.linalg.norm() function
norm_of_vector = np.linalg.norm(vector)

# Print the norm of the vector
print("Norm of the vector:", norm_of_vector)


Norm of the vector: 3.7416573867739413


In [79]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Calculate the dot product
dot_product = np.vdot(a, b)

# Print the dot product
print("Dot product:", dot_product)


Dot product: 32


In [80]:

# استخدام np.dot() لحساب المنتج الداخلي
dot_product = np.dot(a, b)
print("منتج النقطة باستخدام np.dot():", dot_product)  # الناتج: 1*4 + 2*5 + 3*6 = 32

# استخدام np.vdot() لحساب المنتج الداخلي
vdot_product = np.vdot(a, b)
print("منتج النقطة باستخدام np.vdot():", vdot_product)  # الناتج: 1*4 + 2*5 + 3*6 = 32

# مثال مع الأعداد المركبة
c = np.array([1+2j, 3+4j])
d = np.array([5+6j, 7+8j])

# استخدام np.vdot() مع الأعداد المركبة
vdot_complex = np.vdot(c, d)
dot = np.dot(c, d)
print("منتج النقطة بين متجهين مركبين باستخدام np.vdot():", vdot_complex,dot)  # الناتج: (1*5 - 2*6) + (3*7 - 4*8) = (-7-8j)


منتج النقطة باستخدام np.dot(): 32
منتج النقطة باستخدام np.vdot(): 32
منتج النقطة بين متجهين مركبين باستخدام np.vdot(): (70-8j) (-18+68j)


In [81]:
# Define vectors a and b
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Calculate the inner product using np.dot()
inner_product = np.inner(a, b)

# Calculate the outer product using np.outer()
outer_product = np.outer(a, b)

# Print the results
print("Inner product:", inner_product)
print("Outer product:\n", outer_product)


Inner product: 32
Outer product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


### on Matrix

In [82]:
a = np.random.randint(1,9,(3,3))
a

array([[8, 4, 4],
       [2, 3, 7],
       [7, 6, 8]])

In [83]:
np.linalg.det(a)

-47.999999999999986

In [84]:
np.round(np.matmul(np.linalg.inv(a),a)) #matmul == @

array([[ 1., -0.,  0.],
       [ 0.,  1.,  0.],
       [-0.,  0.,  1.]])

In [96]:
a=np.random.randint(1,10,(3,3))
np.linalg.matrix_power(a,3)

array([[ 325,  288,  339],
       [1896, 1717, 2032],
       [2442, 2235, 2631]])

In [98]:
a@a@a

array([[ 325,  288,  339],
       [1896, 1717, 2032],
       [2442, 2235, 2631]])

In [85]:
a.T

array([[8, 2, 7],
       [4, 3, 6],
       [4, 7, 8]])

In [86]:
A = np.array([[1, 2],
              [2, 4]])

# حساب القيم الذاتية والقواعد الذاتية اليمنى
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)

Eigenvalues:
[0. 5.]
Eigenvectors:
[[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]


In [102]:
# Define the coefficient matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Define the right-hand side vector
# Define the coefficients matrix A
A = np.array([[2, 3, -1],
              [4, -2, 3],
              [1, 1, -2]])

# Define the constants vector B
B = np.array([14, 8, 10])

# Solve the system of equations
solution = np.linalg.solve(A, B)
print(f'sol {solution}')

sol [ 4.27586207  1.03448276 -2.34482759]


In [89]:
A**2

array([[ 1,  4],
       [ 4, 16]])